### ISSUE TITLE
Support for symmetric keys

### ISSUE THREAD

**Issue by jerriep** [DuendeArchive/IdentityModel.OidcClient#20]
Is there any plan to support symmetric keys?

It seems there is currently only support for asymmetric keys - and specifically only for RSA keys https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/IdentityTokenValidator.cs#L162

**Comment by leastprivilege** [comment]
no other plans right now.

**Comment by jerriep** [comment]
If I look into this would you consider a PR for this?

**Comment by leastprivilege** [comment]
Look into it first - then let's start a discussion

**Comment by jerriep** [comment]
Yes certainly. Just want to be sure you are open for it before I go down the rabbit hole

**Comment by jerriep** [comment]
Since this library is used on .NET Clients which can be decompiled to access the client secret, we will stick to using asymmetric keys

**Comment by reubenrybnik** [comment]
@leastprivilege Thanks for putting this library together, it's made my life a lot easier so far! I'm currently working on using this library to perform web app to web app SSO with ADP, whose general SSO process is described at https://developers.adp.com/articles/guides/authorization-process-end-user-apps. Unfortunately, I've found that they sign their id token using the HS256 algorithm with the client secret as the key, which currently isn't supported by this library.

Since relying party web apps generally don't make the server-side internals of their product available externally, they usually don't need to be worried about client secrets making their way into the wrong hands, so I believe this is a reasonable if not necessarily optimal way for these to be signed in this case. Also, according to https://tools.ietf.org/html/rfc7518#section-3.1 this appears to be the only algorithm that is currently rated as requiring implementation for use in JSON Web Signing, so that may be one of the reasons that ADP opted for this algorithm over RS256. Therefore, I plan to follow https://tools.ietf.org/html/rfc7518#section-6.4 to add in support for translating JsonWebKey instances with Kty == "oct" to SymmetricSecurityKey instances in method IdentityTokenValidator.ValidateSignature in a fork of this repository so this scenario will work for us.

I'd be happy to make a PR once I'm done if you'd like. If you'd be interested in accepting such a PR, please let me know whether you'd prefer to have me open a new issue or reuse this one.

Since transport security is likely often sufficient for validating the authenticity of the token in the case of SSO between web apps I'd also be willing to consider implementing #21 as an alternative, but from the conversation there I feel like it would be preferable to introduce a change that allows for the use of symmetric keys when a signature generated using a symmetric key is provided rather than allowing for skipping signature validation altogether. Let me know if you disagree.

**Comment by leastprivilege** [comment]
OK - I see. 

I don't like signature skipping. So supporting symmetric keys is preferable. 

I won't have the cycles in the near future to look into this - please fork and make the changes needed to make it work for you. The less changes, the easier it will be to review and potentially merge back.

**Comment by leastprivilege** [comment]
Please open a new issue if this needs further discussion.
