### ISSUE TITLE
Add logout support

### ISSUE THREAD

**Issue by leastprivilege** [DuendeArchive/IdentityModel.OidcClient#25]
Call end_session with configured IBrowser (e.g. to get of persistent cookies if needed).

**Comment by DennisWelu** [comment]
It looks like there was something like this in the v1 OidcClient library: https://github.com/IdentityModel/IdentityModel.OidcClient/blob/master/src/Shared/AuthorizeClient.cs#L96

I've been trying to figure out a workaround to this not being present in v2. I can get the endpoint from the discovered ProviderInformation by doing this kind of thing:

```
            var options = new OidcClientOptions
            {
                Authority = Config.IdentityServerUrl,
                Browser = Browser
            };

            var client = new OidcClient(options);
            var result = await client.PrepareLoginAsync();
            Debug.WriteLine("EndSession url is: " + options.ProviderInformation.EndSessionEndpoint);

```
I'd like to tell the WabBrowser to do something like this:

`await WebAuthenticationBroker.AuthenticateAsync(WebAuthenticationOptions.SilentMode, new Uri(options.ProviderInformation.EndSessionEndpoint));
`

The _reason_ I'm doing this is otherwise I can't see how my native UWP client can clear the cookies that were cached when I checked the "Remember My Login" checkbox on the presented web UI (as per the Hybrid workflow quickstart sample: https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/QuickstartIdentityServer/Quickstart/Account/AccountController.cs)

Thoughts?

**Comment by noufionline** [comment]
HI @leastprivilege and @brockallen. Please give some time for this from your busy schedule. 👍

**Comment by leastprivilege** [comment]
What does logout mean to you in the context of native apps?

**Comment by noufionline** [comment]
I am using a wpf prism app and I tried your method of IBrowser implementing but once the user is logged in and next time the application restarts it showing the concent screen directly. What I need is to have the login screen again. 

I have a logout button which should show the login screen again

**Comment by leastprivilege** [comment]
OK - it is on my todo list. Not sure how soon I will be able to do it.

**Comment by leastprivilege** [comment]
I totally forgot that I added this feature and pushed a 2.4.0-preview1. Give it a try and let me know.

**Comment by leastprivilege** [comment]
the iOS11 client uses the new API now.

**Comment by leastprivilege** [comment]
Feel free to open a new issue if you have problems with that.
