### ISSUE TITLE
ConsoleClient is samples not working?

### ISSUE THREAD

**Issue by JumpAttacker** [DuendeArchive/IdentityModel.OidcClient#297]
Hey, im trying this code https://github.com/IdentityModel/IdentityModel.OidcClient/blob/main/clients/ConsoleClient/Program.cs
but got an error
![image](https://user-images.githubusercontent.com/10989729/112186917-a4603300-8c12-11eb-94a9-049f52ff254d.png)

**Comment by daiplusplus** [comment]
The `ConsoleClient` sample hasn't been updated in 4 years, so it's broken when used with current IdentityServer deployments, but fortunately it's relatively straightforward to fix (even if the investigatory steps (in my case, at least) are nontrivial...)

* Add [NuGet package `Microsoft.Net.Http.Server` v1.1.4](https://www.nuget.org/packages/Microsoft.Net.Http.Server) (despite being marked as deprecated, it works fine for me in .NET 7)
* The `Client` configuration within IdentityServer4 **must** have `RequirePkce = true` and `AllowedGrantTypes` must include `authorization_code` (and not `hybrid`).
* For greater reliability+portability, use `ProcessStartInfo` instead of `Process.Start` and specify `UseShellExecute = true` ([this is required for Linqpad](https://forum.linqpad.net/discussion/2271/process-file-not-found), for example).
* [Since `IdentityModel.OidcClient` v4.x using `ResponseMode = form_post` is no-longer supported](https://github.com/IdentityModel/IdentityModel.OidcClient/issues/325), instead `query` is always used, so change `var formData = GetRequestPostData(context.Request);` to `String formData = request.QueryString;` (and remove the `GetRequestPostData` function entirely).
