### ISSUE TITLE
Closing IBrowser while waiting for LoginAsync

### ISSUE THREAD

**Issue by KaboomPT** [DuendeArchive/IdentityModel.OidcClient#54]
Hello,

Can you please help me obtain a response for a problem that I'm having and that I posted on stackoverflow (https://stackoverflow.com/questions/48586854/oidcclient2-closing-ibrowser-while-waiting-for-loginasync) , please?

In short my problem is related to the events that close the IBrowser (backbutton on Android for example) associated with the OidcClient while awaiting for the LoginResult (var result = await client.LoginAsync();).

Thank you very much!
Ricardo

**Comment by KennyDM** [comment]
Hi, 

I have the same behavior on my side, when cancelling the IBrowser on Android by either hitting the backbutton, or pressing the close button, no result is being returned from the asynchronous client.LoginAsync() call, leaving the viewmodel in a paused state...

Thank you for any insights/workarounds,

Kenny

**Comment by leastprivilege** [comment]
I can't test that here since I am not using Android. Please debug and suggest a fix in a new issue. thanks

**Comment by Brosten** [comment]
This is still an issue. When using ÚWP, the LoginAsync is returned with an error status, if the login-window is closed. But on android, it just doesn't return. I guess the app doesn't get any callback, but probably needs to be handled in the OnResume() somehow...

**Comment by JonnySKK** [comment]
Encountered the same issue. I found that when it authenticates successfully, it correctly triggers OnNewIntent within the activity and therefore hits the line `ActivityMediator.Instance.Send(intent.DataString);` but when its cancelled, i.e. the browser is closed, then it just hangs on loginasync, never triggering OnNewIntent. 

However, on closing the browser, I found it **does** still trigger OnResume. So my workaround was to add a boolean to the activity called "IsAuthenticating" which is set to true just before LoginAsync is triggered, and then add this to OnResume:

```
        protected override void OnResume()
        {
            base.OnResume();

            if (IsAuthenticating)
            {
                ActivityMediator.Instance.Send("com.company.myapp://myauthdomain.eu.auth0.com/android/com.company.myapp/callback");
            }
        }
```

This seems to kill the loginasync and allow the app to continue. I also set the IsAuthenticating to false in OnNewIntent if the login is successful, so that when it hits onresume during a successful login, the ActivityMediator send isn't triggered.
